# Generated by Django 2.1.4 on 2020-10-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflectionalWord', models.CharField(db_index=True, max_length=100, unique=True)),
                ('isVerb', models.NullBooleanField(default=None)),
                ('isLastWord', models.BooleanField(default=False)),
                ('prefix', models.CharField(max_length=100, null=True)),
                ('suffix', models.CharField(max_length=100, null=True)),
                ('stemWord', models.CharField(max_length=100, null=True)),
                ('targetStemWord', models.CharField(max_length=100, null=True)),
                ('isAmbiguous', models.BooleanField(default=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
